dist_a_mean=[3;1];
dist_a_sigma=[1 2;2 5];
dist_b_mean=[1;3];
instance_a=mvnrnd(dist_a_mean,dist_a_sigma,500);
instance_b=mvnrnd(dist_b_mean,dist_a_sigma,500);
combined_d=cat(1,instance_a,instance_b);
mu=mean(combined_d,1);
center_mat=combined_d-mean(combined_d,1);
covar_d=center_mat'*center_mat;
[U_1,S_1,V_1]=svd(covar_d);
%plot(combined_d(:,1),combined_d(:,2),'k*');
figure(3);
plot(instance_b(:,1),instance_b(:,2),'k*',instance_a(:,1),instance_a(:,2),'xy');
covar_ab=instance_a'*instance_b;
[U,S,V]=svd(covar_ab);
x=0:6;
instance_a_mean=mean(instance_a,1);
instance_b_mean=mean(instance_b,1);
x_mean=((instance_a_mean(1)+instance_b_mean(1))/2);
y_mean=((instance_a_mean(2)+instance_b_mean(2))/2);
%3=x*U(1,1)+y*U(2,1);
%y=(x*U(1,1)/U(2,1))-3/U(2,1);
w=0:5;
%y=(V(2,1)*(x-x_mean)/V(1,1))+y_mean;
y=(V_1(2,1)*(x-mu(1))/V_1(1,1))+mu(2);
z=(V(2,2)*(w-x_mean)/V(1,2))+y_mean;
figure(1)
plot(instance_b(:,1),instance_b(:,2),'k*',instance_a(:,1),instance_a(:,2),'xy',x,y);
%ppp=U*S*V';
figure(2)
new_ax=combined_d*V(:,1);
histogram(new_ax)